# Generated by Django 2.2 on 2019-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_auto_20190513_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='projects',
            field=models.ManyToManyField(to='relation.Projects'),
        ),
    ]
