# Generated by Django 2.2 on 2019-07-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None)),
                ('title', models.CharField(default=None, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'All Posts',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
