# Generated by Django 2.2 on 2019-07-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('private', 'Private'), ('draft', 'Draft')], default='publish', max_length=50),
        ),
    ]
